### ISSUE TITLE
This really should be in ember-cli public api

### ISSUE THREAD

**Issue by nightire** [marcemira/ember-shell#11]
I mean this:

https://github.com/marcemira/ember-shell/blob/master/index.js#L48

`isAddon` really should be a public API, consider a PR perhaps? Any way this helps me a lot, thanks.

**Comment by marcemira** [comment]
Hi @nightire, indeed! it's very handy in these sort of addons :smile:
A PR could to `ember-cli` be cool, please be my guest hehe, but I would first ask on slack for the dev-team approval. I'll close this!
